// Generated by scripts/build-docs-nav.mjs. Do not edit manually.

import type { DefaultTheme } from 'vitepress'

export const sidebar: DefaultTheme.SidebarItem[] = 
[
  {
    "text": "Introduction",
    "link": "/"
  },
  {
    "text": "Installation",
    "link": "/installation"
  },
  {
    "text": "Usage",
    "link": "/usage"
  },
  {
    "text": "Development",
    "link": "/development"
  },
  {
    "text": "License",
    "link": "/license"
  }
]
